# Generated by Django 6.0.6 on 2026-08-07 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp_updated_at'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='is_rolled_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='original_payment_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='original_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='rollback_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='rollback_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='payment_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration Fee'), ('SEMESTER', 'Semester Fee'), ('EXAM', 'Exam Fee'), ('LATE', 'Late Registration Fee'), ('ROLLBACK', 'Rollback - Refund')], default='SEMESTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NEED_RESUBMISSION', 'Need Resubmission'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentRollback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(default='ROLLED_BACK', max_length=20)),
                ('rollback_type', models.CharField(choices=[('FULL', 'Full Rollback'), ('PARTIAL', 'Partial Rollback'), ('DEPARTMENT_CHANGE', 'Department Change'), ('ADMIN', 'Admin Rollback'), ('ERROR', 'Error Correction')], default='FULL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks', to='payments.paymentproof')),
                ('rolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_rollbacks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_rollbacks', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
