# Generated by Django 6.0.6 on 2026-08-03 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proctor_images/')),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('face_detected', models.BooleanField(default=True)),
                ('multiple_faces', models.BooleanField(default=False)),
                ('mobile_detected', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_images', to='exams.examattempt')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('COPY_PASTE', 'Copy Paste'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('MULTIPLE_FACES', 'Multiple Faces'), ('FACE_LOST', 'Face Lost')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='exams.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ProctorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_captures', models.IntegerField(default=0)),
                ('suspicious_events', models.IntegerField(default=0)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('auto_flag_threshold', models.IntegerField(default=3)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_session', to='exams.examattempt')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
