# Generated by Django 6.0.6 on 2026-08-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorimage',
            name='eyes_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='gaze_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='gaze_direction',
            field=models.CharField(blank=True, default='CENTER', max_length=20),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='gaze_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='gaze_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='head_tilt_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='head_tilt_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='object_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctorimage',
            name='objects_detected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='gaze_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='head_tilt_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='ml_prediction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='ml_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='proctorsession',
            name='object_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proctorlog',
            name='event_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('COPY_PASTE', 'Copy Paste'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('MULTIPLE_FACES', 'Multiple Faces'), ('FACE_LOST', 'Face Lost'), ('GAZE_AWAY', 'Gaze Away'), ('HEAD_TILTED', 'Head Tilted'), ('EYES_CLOSED', 'Eyes Closed'), ('OBJECT_DETECTED', 'Object Detected'), ('AUTO_FLAGGED', 'Auto Flagged')], max_length=30),
        ),
        migrations.AlterField(
            model_name='proctorsession',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('FLAGGED', 'Flagged'), ('CLEARED', 'Cleared'), ('AUTO_FLAGGED', 'Auto Flagged')], default='PENDING', max_length=20),
        ),
    ]
