# Generated by Django 6.0.6 on 2026-08-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp_updated_at'),
        ('analytics', '0002_idsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentperiod',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 months)'), ('SEMESTER', 'Semester (6 months)'), ('YEARLY', 'Yearly (12 months)')], default='QUARTERLY', max_length=20),
        ),
        migrations.AddField(
            model_name='studentpaymentschedule',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpaymentschedule',
            name='period_number',
            field=models.IntegerField(default=1, help_text='Which period number (1st, 2nd, 3rd...)'),
        ),
        migrations.AddField(
            model_name='studentpaymentschedule',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial'), ('LOCKED', 'Locked - Access Denied')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('COURSE_ENROLLMENT', 'Course Enrollment'), ('EXAM_TAKING', 'Exam Taking'), ('LIVE_CLASS', 'Live Class'), ('COURSE_MATERIALS', 'Course Materials'), ('ASSIGNMENT_SUBMISSION', 'Assignment Submission'), ('RESULTS_VIEWING', 'Results Viewing'), ('CERTIFICATE_DOWNLOAD', 'Certificate Download')], max_length=30)),
                ('is_allowed', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_access', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'service_type')},
            },
        ),
    ]
