# Generated by Django 6.0.6 on 2026-08-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp_updated_at'),
        ('analytics', '0003_paymentperiod_period_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idsequence',
            name='prefix',
            field=models.CharField(default='MAU', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial'), ('LOCKED', 'Locked - Access Denied'), ('PENALTY_PAID', 'Penalty Paid'), ('PENALTY_PENDING', 'Penalty Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentpaymentschedule',
            unique_together={('student', 'fee_structure', 'period_number')},
        ),
        migrations.CreateModel(
            name='StudentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('LOGIN', 'Login Attempt'), ('EXAM', 'Exam Access'), ('COURSE', 'Course Enrollment'), ('ASSIGNMENT', 'Assignment Access'), ('LIVE_CLASS', 'Live Class Access')], max_length=20)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('allowed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
