# Generated by Django 6.0.6 on 2026-08-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_idsequence_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentperiod',
            name='duration_value',
            field=models.IntegerField(default=1, help_text='Number of the selected period type'),
        ),
        migrations.AlterField(
            model_name='paymentperiod',
            name='duration_months',
            field=models.IntegerField(default=1, help_text='Equivalent months for fee calculation'),
        ),
        migrations.AlterField(
            model_name='paymentperiod',
            name='period_type',
            field=models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='MONTHS', max_length=20),
        ),
    ]
