# Generated by Django 6.0.6 on 2026-08-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_paymentperiod_duration_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentperiod',
            options={'ordering': ['duration_value']},
        ),
        migrations.AlterField(
            model_name='paymentperiod',
            name='duration_months',
            field=models.IntegerField(default=0, help_text='Equivalent months for fee calculation (optional)'),
        ),
        migrations.AlterField(
            model_name='paymentperiod',
            name='duration_value',
            field=models.IntegerField(default=10, help_text='Number of the selected period type'),
        ),
        migrations.AlterField(
            model_name='paymentperiod',
            name='period_type',
            field=models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='MINUTES', max_length=20),
        ),
    ]
