# Generated by Django 6.0.6 on 2026-08-15 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_paymentperiod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
