# Generated by Django 6.0.6 on 2026-08-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_studentpaymentschedule_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='period_number',
            field=models.IntegerField(default=1),
        ),
    ]
