# Generated by Django 6.0.6 on 2026-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_studentpaymentschedule_period_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='period_number',
            field=models.IntegerField(default=1, help_text='Which period number (1st, 2nd, 3rd...)'),
        ),
    ]
