# Generated by Django 6.0.6 on 2026-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_studentpaymentschedule_period_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymentschedule',
            name='period_number',
            field=models.IntegerField(default=1),
        ),
    ]
