# Generated by Django 6.0.6 on 2026-08-03 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Administrator'), ('FINANCE', 'Finance Officer'), ('REGISTRAR', 'Registrar'), ('DEPT_HEAD', 'Department Head')], default='STUDENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Summer')], default='1', max_length=2)),
                ('academic_year', models.CharField(max_length=10)),
                ('require_grade_8', models.BooleanField(default=True)),
                ('require_grade_12', models.BooleanField(default=True)),
                ('require_transcript', models.BooleanField(default=True)),
                ('require_other_documents', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_students_per_department', models.IntegerField(default=100)),
                ('allow_senior_registration', models.BooleanField(default=True)),
                ('allow_fresh_registration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('current_semester', models.IntegerField(default=1)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_credits', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('documents_verified', models.BooleanField(default=False)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('registration_type', models.CharField(choices=[('FRESH', 'Fresh Student'), ('SENIOR', 'Senior Student')], default='FRESH', max_length=10)),
                ('grade_8_certificate', models.FileField(blank=True, null=True, upload_to='student_documents/grade8/')),
                ('grade_12_certificate', models.FileField(blank=True, null=True, upload_to='student_documents/grade12/')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='student_documents/transcripts/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='student_documents/other/')),
                ('documents_submitted', models.BooleanField(default=False)),
                ('documents_verified_at', models.DateTimeField(blank=True, null=True)),
                ('registration_complete', models.BooleanField(default=False)),
                ('current_payment_schedule_id', models.IntegerField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('registration_semester', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('qualification', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
