# Generated by Django 6.0.6 on 2026-08-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
