# Generated by Django 6.0.6 on 2026-08-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('OVERDUE_LOCKED', 'Overdue - Locked')], default='PENDING', max_length=20),
        ),
    ]
