# Generated by Django 6.0.6 on 2026-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
