# Generated by Django 6.0.6 on 2026-08-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
