# Generated by Django 6.0.6 on 2026-08-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examattempt_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='ai_flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='ai_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='ai_risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical - Immediate Action Required')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='ai_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='eye_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='face_match_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='fullscreen_exit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='gaze_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='head_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='keystroke_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='lock_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='mouse_movements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='network_latency_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='object_detection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='suspicious_events_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='trust_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
