# Generated by Django 6.0.6 on 2026-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('LINK', 'Link'), ('OTHER', 'Other')], default='DOCUMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='video_attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/videos/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='video_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_type',
            field=models.CharField(choices=[('FILE', 'File Upload'), ('VIDEO', 'Video Upload'), ('LINK', 'Link Submission'), ('TEXT', 'Text Submission')], default='FILE', max_length=10),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_video',
            field=models.FileField(blank=True, null=True, upload_to='submissions/videos/'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='video_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('SLIDE', 'Presentation'), ('DOC', 'Document'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], default='PDF', max_length=20),
        ),
    ]
