# Generated by Django 6.0.6 on 2026-08-03 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_RESUBMIT', 'Payment Resubmission Required'), ('EXAM_SCHEDULED', 'Exam Scheduled'), ('GRADE_RELEASED', 'Grade Released'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('SYSTEM_ALERT', 'System Alert'), ('LIVE_CLASS_STARTED', 'Live Class Started')], default='SYSTEM_ALERT', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
